version: 2.1

commands:
  install-packaged-featuretools:
    description: "install featuretools from source distribution"
    steps:
      - run : |
          source test_env/bin/activate
          python setup.py sdist
          FEATURETOOLS_VERSION=$(python setup.py --version)
          tar -zxvf "dist/featuretools-${FEATURETOOLS_VERSION}.tar.gz"
          pip install -e "featuretools-${FEATURETOOLS_VERSION}/"
          pip install -r "featuretools-${FEATURETOOLS_VERSION}/test-requirements.txt"
  run-packaged-tests:
    description: "run unit tests on packaged testing files"
    steps:
      - run: |
          source test_env/bin/activate
          cd "featuretools-$(python setup.py --version)/"
          pytest

jobs:
  "python-27":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: virtualenv venv_py27
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run: source dev_env/bin/activate && pip install -e .
      - run: source dev_env/bin/activate && pytest

  "python-35":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run: virtualenv venv_py35
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run: source dev_env/bin/activate && pip install -e .
      - run: source dev_env/bin/activate && pytest

  "python-36":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: virtualenv venv_py36
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run: source dev_env/bin/activate && pip install -e .
      - run: source dev_env/bin/activate && pytest

  "python-37":
    working_directory: ~/featuretools
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: virtualenv venv_py37
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run: source dev_env/bin/activate && pip install -e .
      - run: source dev_env/bin/activate && pytest

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - "python-27"
      - "python-35"
      - "python-36"
      - "python-37"