name: Install Test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  install:
    name: ${{ matrix.os }} - ${{ matrix.python_version }} install
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build package
        run: make package
      - name: Install from sdist
        run: |
          pip config --site set global.progress_bar off
          python -m pip install "unpacked_sdist/[complete]"
      - name: Test by importing packages
        run: |
          python -c "import alteryx_open_src_update_checker"
