name: Lint Check
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
  lint_test:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - name: Set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build alteryx_open_src_update_checker package
        run: make package
      - name: Install alteryx_open_src_update_checker with dev requirements
        run: |
          python -m pip install -e .[dev]
      - name: Run lint test
        run: make lint
