on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

name: Unit Tests
jobs:
  unit_tests:
    name: ${{ matrix.python_version }} unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build featuretools_update_checker package
        run: make package_featuretools_update_checker
      - name: Set up pip
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
      - name: Install featuretools_update_checker with test requirements
        run: |
          python -m pip install -e unpacked_sdist/
          python -m pip install -r unpacked_sdist/test-requirements.txt
      - name: Run unit tests
        run: |
          cd unpacked_sdist
          pytest featuretools_update_checker/tests
