name: Unit Tests
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
jobs:
  unit_tests:
    name: ${{ matrix.python_version }} unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    env:
      ALTERYX_OPEN_SRC_UPDATE_CHECKER: False
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Build alteryx_open_src_update_checker package
        run: make package
      - name: Set up pip
        run: |
          pip config --site set global.progress_bar off
          python -m pip install --upgrade pip
      - name: Install alteryx_open_src_update_checker with test requirements
        run: |
          python -m pip install -e unpacked_sdist/[test]
      - name: Run unit tests
        run: |
          cd unpacked_sdist
          pytest alteryx_open_src_update_checker/tests
